name: Audit

on:
  workflow_call:
    inputs:
      go-version:
        description: 1.23.1
        type: string
        required: true
      working-directory:
        description: Working directory to use
        type: string
        default: './'

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}

      - name: Verify Dependencies
        run: go mod verify
        working-directory: ${{ inputs.working-directory }}

      - name: Build
        run: go build -v ./...
        working-directory: ${{ inputs.working-directory }}

      - name: Run go vet
        run: go vet ./...
        working-directory: ${{ inputs.working-directory }}

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: go test -race ./...
        working-directory: ${{ inputs.working-directory }}