name : Products

on:
  push:
    branches: [ main ]
    paths:
      - 'products/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'products/**'
jobs:
  audit:
    uses: ./.github/workflows/audit.yaml
    secrets: inherit
    with:
      go-version: 1.23.1
      working-directory: 'products/'